### ISSUE TITLE
Local DB is not synced to cloud unless call `pushAll`

### ISSUE THREAD

**Issue by lzyy** [caiyue1993/IceCream#116]
## Expected behavior
all works without explicitly call `syncEngine.pushAll()`

## Actual behavior
if `syncEngine.pushAll()` is not called, local db records made by realm is not synced to cloud (no record types and records).

even when `syncEngine.pushAll()` is called, when using demo's Object, `Cat` and `Dog` are pushed, but `Person` is not. (sometimes only `Cat` is pushed)

![image](https://user-images.githubusercontent.com/35974/53153273-d9909600-35f2-11e9-8ce7-267d71fab70e.png)

```swift
let dog = Dog()
let cat = Cat()
let person = Person()
dog.owner = person
        
try! realmdb!.write {
    self.realmdb!.add(dog)
    self.realmdb!.add(cat)
    self.realmdb!.add(person)
}
syncEngine?.pushAll()
```

**Comment by caiyue1993** [comment]
Hi @lzyy , are you using the demo project or not? And how you've initialized the `SyncEngine`?

**Comment by lzyy** [comment]
I mix everything in `didFinishLaunchingWithOptions` method (except Models), nothing appears in Cloudkit Dashboard.

```swift
override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    
    let vc = UIViewController()
    window = UIWindow()
    window.rootViewController = vc

    syncEngine = SyncEngine(objects: [
        SyncObject<Person>(),
        SyncObject<Dog>(),
        SyncObject<Cat>()
        ])
    
    application.registerForRemoteNotifications()
    
    let realm = try! Realm()
    
    let dog = Dog()
    let cat = Cat()
    let person = Person()
    dog.owner = person
    
    try! realm.write {
        realm.add(dog)
        realm.add(cat)
        realm.add(person)
    }
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
```

**Comment by caiyue1993** [comment]
Thanks for the details, I've already figured out the reason of this situation. That is:

When you write data to Realm, the register process has not already finished yet. To be more specific, I mean this line is not being called at that time: https://github.com/caiyue1993/IceCream/blob/ca554ca657dac5282648e8956a3d1a1c4df7a2fb/IceCream/Classes/SyncEngine.swift#L65 

So the timing of writing to local database in your demo is not recommended. I suggest you put the writing action later. And since this may still confuse you, we could add a completion block when `SyncEngine` finishes its initialization process in the later releases.

Thank you again!
