### ISSUE TITLE
pull() method does not seem to work?

### ISSUE THREAD

**Issue by jamesryu108** [caiyue1993/IceCream#138]
I have realm database in my app and I print it before using pull() method. At the beginning, it should show nothing:

> realm db before: Results<exerciseStats> (
> }

Then I use pull method like this:

> syncEngine.pull()

Then I print out the realm database again to see if app has fetched from iCloud:

> realm after2: Results<exerciseStats> (
> )

I observe no changes. What can I do to fetch data right away?

**Comment by jamesryu108** [comment]
pull method does not seem to merge content of cloud with local database right away. It only merges after restarting my app

**Comment by limura** [comment]
I have a similar problem.

I checked the source of SyncEngine.pull () and found the following.

https://github.com/caiyue1993/IceCream/blob/d907729e294a43c0631bc67081c5edc2899d5234/IceCream/Classes/SyncEngine.swift#L69-L71

DatabaseManager.fetchChangesInDatabase() exits immediately after adding processing to the CKDatabase. Please understand that this is an asynchronous process.
Therefore, you are correct in understanding that the process is not complete when the call to SyncEngine.pull() ends.

Also, DatabaseManager.fetchChangesInDatabase() takes one argument, which is called when fetchChangesInDatabase() has finished processing.
Therefore, you may need to use the DatabaseManager.fetchChangesInDatabase() argument (completion) to confirm that SyncEngine.pull() is done.

However, SyncEngine.pull() does not have an argument to pass completion. I don't know why there is no argument.

I think I can avoid the problem for the time being by changing SyncEngine.pull() to receive completion. However, there is already a pull request in the NotificationCenter to do the same.

In response to the pull request, @caiyue1993 says it's unnecessary because you can observe changes using Realm's observe:.

https://github.com/caiyue1993/IceCream/pull/118#issuecomment-478351057

I don't really like using Realm observes to monitor the completion of all Realm models syncing because it's cumbersome, but for now it seems that's the way it is.

**Comment by caiyue1993** [comment]
Gentlemen @limura @jamesryu108 ,

For the latest update please follow #141
