### ISSUE TITLE
Not necessary to use RxSwift in example.

### ISSUE THREAD

**Issue by ADevelopStudio** [caiyue1993/IceCream#146]
Not an issue!
Not necessary to add extra non-needed pod RxRealm/RxSwift because Realm.io already has inbuilt functionality for observing all the changes. Working great.
https://realm.io/docs/swift/latest/#notifications

**Comment by dbmrq** [comment]
Agreed! I didn’t want to use RxSwift and the example made it unnecessarily tricky to separate it from IceCream.

**Comment by caiyue1993** [comment]
Yeah we know it @ADevelopStudio and I'll consider to remove it entirely later. Thank you for the advices :)

**Comment by fstigre** [comment]
Hi @ADevelopStudio, I'm not familiar with `RxSwift` nor `RxRealm` so I would like to remove them if they're not needed. Based on the Example project shipped with `IceCream`, what are the parts that would need to change in order to remove them? I see that method `bind()` uses it, is this the only method using `RxSwift/RxRealm` or are there any other parts that would need to be changed?

**Comment by ADevelopStudio** [comment]
@fstigre remove everything from RxSwift, including   Observable/subscribe/disposed, etc.. everything you do not know how to use. And to track all the changes use built-in notifications from Realm: https://realm.io/docs/swift/latest/#notifications

**Comment by fstigre** [comment]
Got it. I thought `RxSwift` was also used somewhere in the framework. It's working great without it. Thanks.
