### ISSUE TITLE
Use recordName as Realm primaryKey

### ISSUE THREAD

**Issue by moritzsternemann** [caiyue1993/IceCream#160]
This is kind of a question and issue at the same time. Doesn't really fit the issue template so I'll describe it as good as I can.

My iCloud database uses the _recordName_ as the unique identifier of objects and I'd like to replicate that in the local Realm database.
Unfortunately I couldn't even figure out if it's possible to add the _recordName_ to the Realm database as a field and therefore obviously can't use it as my primary key.

Am I overlooking something here or are there roadblocks preventing the implementation of this?

**Comment by caiyue1993** [comment]
Hi @moritzsternemann ,

> My iCloud database uses the recordName as the unique identifier of objects and I'd like to replicate that in the local Realm database.

In my opinion, it is not possible to achieve this in the way that you pointed out above. Because Realm requires a primary key for each object type.

But however if you want to add the `recordName` to the Realm database as a field. It it definitely OK but it will have collision to the current version of IceCream, which means you have to tweak some code to suit your needs. As for the time being, IceCream will regard `recordName` as primaryKey and use it to query for object when parsing `CKRecord` in sync process.

**Comment by caiyue1993** [comment]
Feel free to comment if you still has questions :)
