### ISSUE TITLE
Merge local data and in the cloud

### ISSUE THREAD

**Issue by ivanvorobei** [caiyue1993/IceCream#170]
Problems with merge local changes with disable sync. See more details: 

## Steps to reproduce the problem
Launch app, add any object. For example `Dog` with name. It sync, all correct. 
After set `syncEngine` to nil and launch app. (emulate off wi-fi). Change name for Dog, and after launch app again with  `syncEngine `. Dog restore old name. 

## Expected behavior
New name of `Dog` should upload to CloudKit. Check newest changes and merge.

## Actual behavior
Dog restored old name. 

## Maybe
Not allowed set `syncEngine` to `nil` for disable sync? Maybe sync always need init in appDelegate?

**Comment by caiyue1993** [comment]
Hi @ivanvorobei ,

Setting `syncEngine` to `nil` is not a suggested way to disable sync. Actually as you said, SyncEngine should always get initialized in AppDelegate. As https://github.com/caiyue1993/IceCream/blob/1d6cc98831a743864176e0cc9dbddf8d0ad2e0cc/IceCream/Classes/SyncEngine.swift#L47 indicates, when app gets launched again the `syncEngine` will try to `resumeLongLivedOperationIfPossible` in that method so that it will upload that tweaked `Dog` to iCloud.
Also, IceCream provides `pull` and `pushAll` methods to suit this situation, which is used to fetch latest cloud changes and push all local changes to cloud. You could have a try.

**Comment by caiyue1993** [comment]
However please take an eye on #148. These issues seem to have something in common. We could make it better in the future.
