### ISSUE TITLE
IceCream Example not working as expected

### ISSUE THREAD

**Issue by rs658726** [caiyue1993/IceCream#174]
First of, thank you for such a great template.

## Expected behavior

Real time sync and order of lists preserved across devices.

## Actual behavior

I might have a different understanding of what IceCream does, but after running the example project on 2 different simulator devices side by side, I noticed that data would rarely sync in real time (I'd often have to restart the app to see changes appear). Another unexpected behavior I noticed is the fact that the sync mechanism doesn't preserve the order of lists across devices.

## Steps to reproduce the problem

The real time syncing issue I described can easily be reproduced, so instead I'll give an example of the list order problem I'm seeing:

Say I add task 1 to device A and right after (before the syncing happens) I add task 2 to device B.  After the syncing occurs I end up with the following:

Device A
Task 1
Task 2

Device B 
Task 2
Task 1

**Comment by caiyue1993** [comment]
Hi @rs658726 , 
Thank you for the feedback. However, I suggest trying the example with the hardware devices instead of the simulator. As the `didReceiveRemoteNotification` method which real time sync relies on will not be triggered on the simulator.
As for the second issue, that's because the newly added item is appended to the local Realm database instead of totally refreshed with the data in the cloud. In the other words, it is an issue of the example project instead of the `IceCream`. 
For more you could check the source code :)
