### ISSUE TITLE
Add pre/post hooks for model object updates

### ISSUE THREAD

**Issue by joelkraut** [caiyue1993/IceCream#19]
Example: I index my model objects into CoreSpotlight for searching. It would be great if `SyncEngine` had a `postUpdate` block in which I could do additional work on the updated model. Maybe like
```
class SyncEngine {
…
var postUpdate: ((added: [T], deleted: [T], updated: [T]) -> ()) = { _, _, _ in }
…
```
and then invoke it in `fetchChangesInZone` after all the `changesOp` blocks complete. Or if it would make it easier, one block per each: `postAdd`, `postUpdate`, `postDelete`.

I'm happy to do this in a pull request if it seems like a good direction.

**Comment by caiyue1993** [comment]
Hi @joelkraut , thanks for raising this new issue. Actually I am not very clear of your requirements and need your confirmation. So you want to: 

Notify your app of the changed record/object in the `changesOp`, right?

**Comment by insidegui** [comment]
@joelkraut Any reason you can't use regular [Realm notifications](https://realm.io/docs/swift/latest/#notifications) for this?

**Comment by joelkraut** [comment]
@caiyue1993: yes, exactly. It could be a notification rather than a completion block, doesn't matter much. Basically I want to be able to act on added/deleted/changed objects once they've been changed from CloudKit.

@insidegui: I'm happy to be wrong here, but I think that would be too general for my purposes. I also do a lot of writing to the database locally (ie not from CloudKit changes), and I don't necessarily want to treat those changes the same way. I don't think Realm notifications provide a mechanism to say in what context the change happened. I could make everything go through the same mechanism, but that might lead to some spaghetti-like code if I'm specifically avoiding acting on new objects when I make them so that a global notification handler can deal with them later.

**Comment by caiyue1993** [comment]
@joelkraut Well, I guess that I've known what you wanna do. You want to act differently from data changes from local and data changes from CloudKit.

So: 
- If you don't need to do anything due to the local database change, I suggest you looking at the `commitWrite(withoutNotifying:)` method in Realm. 
- If you need to do something due to the local database change, why you don't just do something right there yourself?

So in my opinion, IceCream might not need to add this feature for now(If added, that might lead to some spaghetti-like code to IceCream instead).

However, if you insist you could fork this project, do your own changes and use that. 🙂

**Comment by caiyue1993** [comment]
I'm gonna close this issue for now. If you have more ideas, we could reopen it. Thanks man!
