### ISSUE TITLE
Cannot find type 'ListBase' in scope

### ISSUE THREAD

**Issue by Mr-ZNN** [caiyue1993/IceCream#243]
Compile the project, the following code reports an error

/// We may get List<Cat> here
/// The item cannot be casted as List<Object>
/// It can be casted at a low-level type ListBase
**_guard let list = item as? ListBase, list.count > 0 else { break }_**
var referenceArray = [CKRecord.Reference]()
let wrappedArray = list._rlmArray

**Comment by mrezk** [comment]
I am having the same issue. This issue started happening at Realm Cocoa v10.8.0.
No issues with v10.7.7.

**Comment by elliotcz97** [comment]
Had the same issue. You have to use an older version of Realm, to get it to work!

**Comment by kenton7** [comment]
Same issue. Using Realm v10.7.7 fixed problem, but fix this issue with last version of Realm.

**Comment by timefrancesco** [comment]
I've updated it on my fork to be compatible, but not 100% sure if it works properly, can someone help test it?
https://github.com/timefrancesco/IceCream 

* Requires Realm > 10.8

**Comment by Mr-ZNN** [comment]
This issue is currently resolved with Realm v10.7.7 and is expected to be compatible with iCream.

**Comment by dbmrq** [comment]
> I've updated it on my fork to be compatible, but not 100% sure if it works properly, can someone help test it?
> https://github.com/timefrancesco/IceCream
> 
> * Requires Realm > 10.8

Well, I have no idea what you did there, but it seems to be working for me! 🍻

**Comment by mrezk** [comment]
@caiyue1993  this issue blocks IceCream from using any version of Realm higher or equal than 10.8. The latest RealmSwift version is now 10.15.1. Have you considered applying timefrancesco's patch? (https://github.com/timefrancesco/IceCream/commit/606cf63046cae16d8f1b28e6b58a91a7af9f66fd)

**Comment by caiyue1993** [comment]
> @caiyue1993 this issue blocks IceCream from using any version of Realm higher or equal than 10.8. The latest RealmSwift version is now 10.15.1. Have you considered applying timefrancesco's patch? ([timefrancesco@606cf63](https://github.com/timefrancesco/IceCream/commit/606cf63046cae16d8f1b28e6b58a91a7af9f66fd))

Hi @mrezk, sorry now I have no plan to support Realm higher than 10.8 version. And have you guys tested the patch? I don't think `dynamicList` could suit our cases here. However I'll look deeper later

**Comment by dbmrq** [comment]
> > I've updated it on my fork to be compatible, but not 100% sure if it works properly, can someone help test it?
> > https://github.com/timefrancesco/IceCream
> > 
> > * Requires Realm > 10.8
> 
> @timefrancesco Well, I have no idea what you did there, but it seems to be working for me! 🍻

Turns out this stopped working for me :/

Like I said [here](https://github.com/dbmrq/IceCream/commit/ca7bdfdc60bbe8699d1780c7e2e32fcc325e5321), I started getting errors like "cannot use an empty list to initialize a new field" and then sync operations won't even complete at all. :/

**Comment by caiyue1993** [comment]
Hi guys,

I suggest you using Realm before the version of 10.0.0 **for the time being**(which is v5.3.2 the last former one). Here is the reasons:

1. Here is the release note of Realm 10 version: https://github.com/realm/realm-swift/blob/master/CHANGELOG.md#1000-beta1-release-notes-2020-06-08. Since Realm is acquired by MongoDB, the main break changes of the version 10 is "_We no longer support Realm Cloud (legacy), but instead the new "MongoDB Realm" Cloud._". Since you're tempting to use iCloud as cloud sync solution, I haven't seen the sufficient reason to migrate to the version 10.

2. I don't know why the developers at MongoDB Realm remove the support of `ListBase` and haven't regarded it as a break change: https://github.com/realm/realm-swift/commit/381eda15a9e2e1610baf4a764901cbfba005f078#diff-0165363078a304086de8efc5042f6a26f299760d001df8e433ee0db147c40c1e. It's happening in their 10.8.0 releases and what depresses me is they even haven't mentioned it in their 10.8.0 release note.

3. If you want to use the SwiftUI features of Realm, I suggest you could wrap as you needs now. I've checked their change logs recently and there still are many fixes each version. So use the legacy stable version will not be a bad choice, actually will be a fair one.

Sorry for the delay of the response and the maintenance as I was busy at company. The good news is I've quitted my job and start my indie hacker life! So I can spend more time on the open source project and crafting my own app(which uses IceCream, absolutely:). Let's make IceCream great again.

**Comment by blackturtle2** [comment]
@caiyue1993  I was already using realm `10.22.0`, is it too late to use the IceCream? 😭
There doesn't seem to be a way to downgrade realm.
I am very sorry for uploading the realm version. 😞

**Comment by caiyue1993** [comment]
@blackturtle2 Hi, please check the PR #256. You could use that implementation in advance before getting merged into the master branch. 
Don't cry! There must be a way out. 😄
