### ISSUE TITLE
Swift 4.2 support?

### ISSUE THREAD

**Issue by SirArkimedes** [caiyue1993/IceCream#87]
## Expected behavior

IceCream works with the latest version of Swift!

## Actual behavior

IceCream works with Swift 4.0, but not Swift 4.2. These errors occur:

<img width="271" alt="screen shot 2018-09-19 at 10 18 26 pm" src="https://user-images.githubusercontent.com/3119506/45794050-5a212400-bc5a-11e8-9160-e74b8c054f1f.png">

## Steps to reproduce the problem

Create a new project with Xcode 10 or later, add IceCream as a dependency using CocoaPods, then build.

## Note
I can have a PR ready, if desired!

**Comment by SirArkimedes** [comment]
This is already happening here: 5a4cd70ff90e579a88501cbcebb1f14f6129e265

**Comment by caiyue1993** [comment]
Hi @SirArkimedes , are you using CocoaPods or Carthage?

**Comment by SirArkimedes** [comment]
CocoaPods!

**Comment by caiyue1993** [comment]
For the time being,

If you're using CocoaPods, I suggest you using `post_install` hook in your Podfile and set the `SWIFT_VERSION` of IceCream to 4.0. It will build IceCream with Swift 4.0 compiler(since Apple told us that Swift 3, 4, and 4.2 targets can coexist and link together). The official Swift 4.2 support of  IceCream for CocoaPods will be released soon. Just be patient.

If you're using Carthage, [swift-4.2](https://github.com/caiyue1993/IceCream/tree/swift-4.2) branch has already been provided. Just change that in your Cartfile.

**Comment by caiyue1993** [comment]
`swift-4.2` branch was merged. IceCream 1.7.0 is out adding support for Xcode 10 / Swift 4.2, don't forget to check that out!
