### ISSUE TITLE
Does IceCream support Realm data model migrations?

### ISSUE THREAD

**Issue by OxenBoxen** [caiyue1993/IceCream#89]
I'm considering leveraging IceCream for a personal project I'm working on currently. I'm concerned with how IceCream handles realm data model migrations.

Thanks.

**Comment by caiyue1993** [comment]
Hi @OxenBoxen , just be my guest. 

IceCream has already handled this situation. When you do local migrations of Realm Database, the notifications changes block will be triggered: https://github.com/caiyue1993/IceCream/blob/117126c42c92d55bc0d050edbc082e816d37910c/IceCream/Classes/SyncObject.swift#L114

However, since we did nothing on the `.initial` change case for now, I don't know whether the fact will suit your needs(actually I'm considering add some sync action in `.initial` case #84). I highly suggest you debug a demo first and just raise an issue if encountered any problems. Thanks.
