### ISSUE TITLE
Reference syncing problem

### ISSUE THREAD

**Issue by frasza** [caiyue1993/IceCream#95]
## Expected behavior

I create the object with specific properties (in my app example Habit with habit infos) and additional objects referencing to this object (one-to-many) - statuses for specific dates related to habit. Initial sync seems to be working well, because data gets stored and is visible on iCloud dashboard.

## Actual behavior(optional)

Up to this point, data is synced but if I remove the application and install in on device again, some of the items are missing, even tho they are stored in iCloud. Same goes if I install the app on other device.

## Steps to reproduce the problem(optional)

1. First I create the habit and change status to success on certain dates (simulator):
![1](https://user-images.githubusercontent.com/22049682/47267802-d7d19b80-d548-11e8-97df-435d1e242329.png)

2. I install the app on my real device, open the calendar and statuses on speicfic dates are missing (18):
![img_de5c098a367c-1](https://user-images.githubusercontent.com/22049682/47267829-1404fc00-d549-11e8-8bf4-182722944860.jpeg)
As you can see on my dashboard, there are 7 records and 18th day is there as well..
![image](https://user-images.githubusercontent.com/22049682/47268035-b1612f80-d54b-11e8-8d6a-00055250f13d.png)

3. Even futher, if I add more statuses and reinstall the app then even more of them are missing.
Example with more statuses going away:
![img_c5073ab15ce8-1](https://user-images.githubusercontent.com/22049682/47267912-3ba89400-d54a-11e8-809b-5d6da27979e7.jpeg)
![2](https://user-images.githubusercontent.com/22049682/47267914-4531fc00-d54a-11e8-8341-097d651b11d6.png)

Seems like I am having some problems with syncing. @caiyue1993,  any idea? If you need more information about code, let me know.

**Comment by frasza** [comment]
I have tried to print out 2 example dates and it seems like one has referenced habit 'nil' but in iCloud dashboard it DOES have the reference.

`2018-10-18 23BA5881-49D8-4164-982B-F68C4775C8C3 Success **nil*
2018-10-17 E3468BB8-E813-45F8-898C-052F20CF9DAA Success Optional(Habit {
	id = 12A6F631-6C96-421D-88DD-57EFCC755366;
	category = Social;
	type = Affirmation;
	name = First habit;
	habitDescription = lol;
	color = #E9AB61FF;
	numberOfSuccess = 7;
	targetNumber = 20;
	relativeSuccess = 35;
	isDeleted = 0;
})`

**Comment by phuongvb** [comment]
I have same problem with my own app. The app is installed in only 1 device. I remove then re-install it. Reference (relation object) of some objects is nil in local, but it is available in Cloud Dashboard.
Whenever I delete and re-install app, synchronize result is different.

**Comment by danpratt** [comment]
I found a temporary workaround.

1) In Realm class that you are setting the reference in, create a new @objc dynamic var to track the id as a string.

2) Check for null values on the reference; if you find one, simply search for the object you are trying to reference with the string version of the id, and write the reference in Realm. (since the only thing IceCream's import is having trouble with is the reference, and not a primitive type, it will load the string from iCloud).

3) iCloud sync should work properly again, and missing references are restored.

Hopefully this makes sense, and that it helps before this bug is fixed.

**Comment by iPhoNewsRO** [comment]
@danpratt can you provide some code example? i'm trying to use this walkaround but i still get the same issues

**Comment by danpratt** [comment]
> @danpratt can you provide some code example? i'm trying to use this walkaround but i still get the same issues

Basically the idea is this.  Let's say you have a person object, and an ice cream object.  The person object uses a UUID for the primary key, and is LinkingObjects of type ice cream.  Since the IceCream pod sometimes drops the reference when restoring from iCloud, we store a string version of the person's UUID as a realm property inside the ice cream object.  When you establish the link between Person and Ice Cream, just make sure you set the UUID from person to the personID property on the ice cream object.

`class Person: Object {
    @objc dynamic var id = UUID().uuidString
    @objc dynamic var name = ""
    let iceCream = LinkingObjects(fromType: IceCream.self, property: "person")
    
    // use id for primary key
    override class func primaryKey() -> String? {
        return "id"
    }
}

class IceCream: Object {
    @objc dynamic var flavor: String = ""
    @objc dynamic var personID: String = ""
    @objc dynamic var person: Person?
}`

Now, somewhere in your code, you can check to see if you have any IceCream objects with a nil value for Person.  If there are, you can use the personID property (which will not be lost in an iCloud sync), to find the correct person object, and set the person property in IceCream back to the correct Person, fixing the nil reference problem.

Hopefully that makes sense, and is helpful.

**Comment by iPhoNewsRO** [comment]
@danpratt thank you! i got it working
